# Generated by Django 4.2.1 on 2023-05-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True, unique=True)),
                ('vk_id', models.IntegerField(null=True, unique=True)),
                ('tg_id', models.IntegerField(null=True, unique=True)),
                ('tg_nick', models.CharField(null=True)),
                ('tg_url', models.CharField(null=True)),
                ('name', models.CharField()),
                ('bdate', models.DateField()),
                ('sex', models.IntegerField()),
                ('city', models.CharField(null=True)),
                ('geo_lat', models.FloatField()),
                ('geo_long', models.FloatField()),
                ('description', models.CharField(null=True)),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('find_m', models.IntegerField()),
                ('find_f', models.IntegerField()),
                ('purp1', models.IntegerField()),
                ('purp2', models.IntegerField()),
                ('purp3', models.IntegerField()),
                ('purp4', models.IntegerField()),
                ('purp5', models.IntegerField()),
                ('ch_name', models.DateTimeField(null=True)),
                ('ch_sex', models.DateTimeField(null=True)),
                ('ch_bdate', models.DateTimeField(null=True)),
                ('created', models.DateField()),
                ('deactivated', models.DateTimeField(null=True)),
                ('last_usage', models.DateTimeField()),
                ('offer_kilometrage', models.IntegerField(null=True)),
                ('offer_ofset', models.IntegerField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Offerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Matchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('profile_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
                ('profile_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(null=True)),
                ('url_vk', models.CharField(null=True)),
                ('tg_id', models.CharField(null=True)),
                ('description', models.CharField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Complaintlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField()),
                ('description', models.CharField(null=True)),
                ('images', models.CharField(null=True)),
                ('status', models.CharField()),
                ('date', models.DateTimeField()),
                ('complain_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.profile')),
            ],
        ),
    ]
